# Generated by Django 4.0.3 on 2022-03-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
